# ---------- BASE : ROS 2 Rolling (multi-arch amd64/arm64) ----------
    FROM ros:rolling-ros-base AS build

    # 1. dépendances de compilation
    RUN apt-get update && apt-get install -y \
            build-essential cmake git libasio-dev \
     && rm -rf /var/lib/apt/lists/*
    
    # 2. workspace
    ENV WS=/ws
    RUN mkdir -p $WS/src
    WORKDIR $WS
    
    # 3. copier les sources (seul le package drone_middleware ici)
    COPY ./drone_middleware  src/drone_middleware
    
    # 4. résoud dépendances système manquantes (pas de --rosdistro car rolling)
    RUN . /opt/ros/rolling/setup.sh && \
        rosdep update && \
        rosdep install --from-paths src --ignore-src -r -y
    
    # 5. build
    RUN . /opt/ros/rolling/setup.sh && \
        colcon build --packages-select drone_middleware \
                     --cmake-args -DCMAKE_BUILD_TYPE=Release
    
    # ---------- RUNTIME (image allégée) ----------
    FROM ros:rolling-ros-base AS runtime
    ENV WS=/ws
    COPY --from=build /ws/install ${WS}/install
    
    # Set-up ROS environment
    RUN echo "source ${WS}/install/setup.bash" >> /etc/bash.bashrc
    ENTRYPOINT ["/bin/bash","-c","source ${WS}/install/setup.bash && exec \"$@\"","--"]
    CMD ["ros2","run","drone_middleware","dmw_node"]
    